namespace AF
{
    public enum GoogleLanguage
    {
        None,
        Afrikaans,
        Albanian,
        Amharic,
        Arabic,
        Armenian,
        Azerbaijani,
        Basque,
        Belarusian,
        Bengali,
        Bosnian,
        Bulgarian,
        Catalan,
        ChineseSimplified,
        ChineseTraditional,
        Croatian,
        Czech,
        Danish,
        Dutch,
        English,
        Estonian,
        Filipino,
        Finnish,
        French,
        Galician,
        Georgian,
        German,
        Greek,
        Gujarati,
        HaitianCreole,
        Hebrew,
        Hindi,
        Hungarian,
        Icelandic,
        Indonesian,
        Irish,
        Italian,
        Japanese,
        Kannada,
        Kazakh,
        Khmer,
        Korean,
        Latvian,
        Lithuanian,
        Macedonian,
        Malay,
        Malayalam,
        Marathi,
        Mongolian,
        Nepali,
        Norwegian,
        Persian,
        Polish,
        Portuguese,
        Punjabi,
        Romanian,
        Russian,
        Serbian,
        Slovak,
        Slovenian,
        Spanish,
        Swahili,
        Swedish,
        Tamil,
        Telugu,
        Thai,
        Turkish,
        Ukrainian,
        Urdu,
        Vietnamese,
        Welsh
    }

    public static class GoogleLanguageExtensions
    {
        public static string ToCode(this GoogleLanguage language)
        {
            return language switch
            {
                GoogleLanguage.None => "",
                GoogleLanguage.Afrikaans => "af",
                GoogleLanguage.Albanian => "sq",
                GoogleLanguage.Amharic => "am",
                GoogleLanguage.Arabic => "ar",
                GoogleLanguage.Armenian => "hy",
                GoogleLanguage.Azerbaijani => "az",
                GoogleLanguage.Basque => "eu",
                GoogleLanguage.Belarusian => "be",
                GoogleLanguage.Bengali => "bn",
                GoogleLanguage.Bosnian => "bs",
                GoogleLanguage.Bulgarian => "bg",
                GoogleLanguage.Catalan => "ca",
                GoogleLanguage.ChineseSimplified => "zh-CN",
                GoogleLanguage.ChineseTraditional => "zh-TW",
                GoogleLanguage.Croatian => "hr",
                GoogleLanguage.Czech => "cs",
                GoogleLanguage.Danish => "da",
                GoogleLanguage.Dutch => "nl",
                GoogleLanguage.English => "en",
                GoogleLanguage.Estonian => "et",
                GoogleLanguage.Filipino => "tl",
                GoogleLanguage.Finnish => "fi",
                GoogleLanguage.French => "fr",
                GoogleLanguage.Galician => "gl",
                GoogleLanguage.Georgian => "ka",
                GoogleLanguage.German => "de",
                GoogleLanguage.Greek => "el",
                GoogleLanguage.Gujarati => "gu",
                GoogleLanguage.HaitianCreole => "ht",
                GoogleLanguage.Hebrew => "iw",
                GoogleLanguage.Hindi => "hi",
                GoogleLanguage.Hungarian => "hu",
                GoogleLanguage.Icelandic => "is",
                GoogleLanguage.Indonesian => "id",
                GoogleLanguage.Irish => "ga",
                GoogleLanguage.Italian => "it",
                GoogleLanguage.Japanese => "ja",
                GoogleLanguage.Kannada => "kn",
                GoogleLanguage.Kazakh => "kk",
                GoogleLanguage.Khmer => "km",
                GoogleLanguage.Korean => "ko",
                GoogleLanguage.Latvian => "lv",
                GoogleLanguage.Lithuanian => "lt",
                GoogleLanguage.Macedonian => "mk",
                GoogleLanguage.Malay => "ms",
                GoogleLanguage.Malayalam => "ml",
                GoogleLanguage.Marathi => "mr",
                GoogleLanguage.Mongolian => "mn",
                GoogleLanguage.Nepali => "ne",
                GoogleLanguage.Norwegian => "no",
                GoogleLanguage.Persian => "fa",
                GoogleLanguage.Polish => "pl",
                GoogleLanguage.Portuguese => "pt",
                GoogleLanguage.Punjabi => "pa",
                GoogleLanguage.Romanian => "ro",
                GoogleLanguage.Russian => "ru",
                GoogleLanguage.Serbian => "sr",
                GoogleLanguage.Slovak => "sk",
                GoogleLanguage.Slovenian => "sl",
                GoogleLanguage.Spanish => "es",
                GoogleLanguage.Swahili => "sw",
                GoogleLanguage.Swedish => "sv",
                GoogleLanguage.Tamil => "ta",
                GoogleLanguage.Telugu => "te",
                GoogleLanguage.Thai => "th",
                GoogleLanguage.Turkish => "tr",
                GoogleLanguage.Ukrainian => "uk",
                GoogleLanguage.Urdu => "ur",
                GoogleLanguage.Vietnamese => "vi",
                GoogleLanguage.Welsh => "cy",
                _ => ""
            };
        }
    }
}
